version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "09:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: eslint
    versions:
    - 7.23.0
    - 7.24.0
  - dependency-name: "@graphql-codegen/typescript-graphql-request"
    versions:
    - 3.1.0
  - dependency-name: "@types/react"
    versions:
    - 17.0.3
  - dependency-name: "@graphql-codegen/typescript-operations"
    versions:
    - 1.17.15
  - dependency-name: typescript
    versions:
    - 4.2.3
  - dependency-name: next
    versions:
    - 10.1.2
  - dependency-name: "@types/node"
    versions:
    - 14.14.37
